from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name = QtWidgets.QComboBox(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(20, 10, 200, 23))
        self.name.setObjectName("name")
        self.name.addItem('Арсеньев')
        self.name.addItem('Кувшинов')
        self.name.addItem('Голубков')
        self.name.addItem('Полетаев')
        self.name.addItem('Сухов')
        self.name.addItem('Кошелев')
        self.name.addItem('Куренкова')
        self.name.addItem('Мочалов')
        self.mounth = QtWidgets.QComboBox(self.centralwidget)
        self.mounth.setGeometry(QtCore.QRect(240, 10, 110, 23))
        self.mounth.setObjectName("mounth")
        self.mounth.addItem('Январь')
        self.mounth.addItem('Февраль')
        self.mounth.addItem('Март')
        self.mounth.addItem('Апрель')
        self.mounth.addItem('Май')
        self.mounth.addItem('Июнь')
        self.mounth.addItem('Июль')
        self.mounth.addItem('Август')
        self.mounth.addItem('Сентябрь')
        self.mounth.addItem('Октябрь')
        self.mounth.addItem('Ноябрь')
        self.mounth.addItem('Декабрь')
        self.year = QtWidgets.QComboBox(self.centralwidget)
        self.year.setGeometry(QtCore.QRect(370, 10, 60, 23))
        self.year.setObjectName("year")
        self.year.addItem('2020')
        self.year.addItem('2021')
        self.year.addItem('2022')
        self.year.addItem('2023')
        self.year.addItem('2024')
        self.year.addItem('2025')
        self.year.addItem('2026')
        self.year.addItem('2027')
        self.year.addItem('2028')
        self.year.addItem('2029')
        self.object = QtWidgets.QLineEdit(self.centralwidget)
        self.object.setGeometry(QtCore.QRect(20, 40, 130, 23))
        self.object.setObjectName("object")
        self.hour = QtWidgets.QLineEdit(self.centralwidget)
        self.hour.setGeometry(QtCore.QRect(170, 40, 50, 23))
        self.hour.setObjectName("hour")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(240, 40, 190, 160))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateButton.setGeometry(QtCore.QRect(20, 100, 90, 23))
        self.updateButton.setObjectName("updateButton")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(130, 100, 90, 23))
        self.addButton.setObjectName("addButton")
        self.editButton = QtWidgets.QPushButton(self.centralwidget)
        self.editButton.setGeometry(QtCore.QRect(20, 130, 90, 23))
        self.editButton.setObjectName("editButton")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(130, 130, 90, 23))
        self.deleteButton.setObjectName("deleteButton")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(20, 177, 130, 23))
        self.saveButton.setObjectName("saveButton")
        self.lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd.setGeometry(QtCore.QRect(170, 177, 50, 23))
        self.lcd.setStyleSheet('color: black;')
        self.lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd.setObjectName("lcd")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Объект"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "н/ч"))
        self.updateButton.setText(_translate("MainWindow", "Загрузить из БД"))
        self.addButton.setText(_translate("MainWindow", "Добавить>>"))
        self.editButton.setText(_translate("MainWindow", "Редактировать"))
        self.deleteButton.setText(_translate("MainWindow", "Удалить<<"))
        self.saveButton.setText(_translate("MainWindow", "Сохранить табель"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
